# Generated by Django 5.2 on 2025-05-07 03:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('finanzas', '0002_alter_transaccion_options_transaccion_fecha_creacion_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='transaccion',
            options={'get_latest_by': 'fecha_creacion', 'ordering': ['-fecha_creacion']},
        ),
        migrations.AddField(
            model_name='transaccion',
            name='saldo_acumulado',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=12),
        ),
    ]
